#! /bin/sh

chosen=$(printf "  Power Off\n  Restart\n  Sleep\n  Lock" | rofi -dmenu -i)

case "$chosen" in
        "  Power Off") systemctl poweroff ;;
        "  Restart") systemctl reboot ;;
        "  Sleep") systemctl suspend ;;
        "  Lock") pkill -KILL -u ${USER} ;;
        *) exit 1 ;;
esac